///////////////////////////////////////////////////////////////////////
/// POINTER.JS  ///////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////
//Controls the graphical output of the model's prediction in the
//user's browser window.

$(document).ready(function() {

	const $pointer = $('#pointer');
	const pointer_size = $pointer.outerWidth();

	//global pointer object which displays the prediction generated by the neural network
	window.pointer = {
		pointer : $pointer,
		pointer_size : pointer_size,
		isHidden : false,
		
		movePointer: function(x, y){
			$pointer.css('left', x + 'px');
			$pointer.css('top', y + 'px');
		},
	};
	
});
